# Generated by Django 5.2.11 on 2026-03-28 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_incidente_id_alter_sistema_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='resolvido',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='incidente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incidente',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Instável', 'Instável'), ('Fora do Ar', 'Fora do Ar')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidente',
            name='sistema',
            field=models.CharField(choices=[('Portal do Aluno', 'Portal do Aluno'), ('Lyceum', 'Lyceum'), ('Chamada', 'Chamada')], max_length=50),
        ),
    ]
