# Generated by Django 5.2.11 on 2026-04-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_incidente_data_inicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sistema',
        ),
        migrations.AddField(
            model_name='incidente',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='incidente',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Instável', 'Instável'), ('Fora do Ar', 'Fora do Ar')], default='Funcionando', max_length=20),
        ),
    ]
