# Generated by Django 6.0.2 on 2026-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_incidente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
