# Generated by Django 5.2.11 on 2026-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_incidente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
