# Generated by Django 5.2.11 on 2026-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_incidente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
