# Generated by Django 5.2.11 on 2026-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_incidente_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Instável', 'Instável'), ('Fora do Ar', 'Fora do Ar')], default='Funcionando', max_length=50),
        ),
    ]
